import type { FieldDef } from "./types"

/** 全量字段目录：由旧版 app.js schemas 迁移生成；json 类字段映射到结构化构建器 */
export const FIELDS_BY_RESOURCE: Record<string, FieldDef[]> = {
  dashboard: [
    { key: "metric", label: "指标", type: "text" },
    { key: "value", label: "当前值", type: "text" },
  ],
  config: [
    { key: "key", label: "配置键", type: "text" },
    { key: "value", label: "值", type: "text" },
    { key: "value_type", label: "类型", type: "select", options: ["int","float","string","bool","json"] },
    { key: "description", label: "说明", type: "textarea" },
  ],
  features: [
    { key: "key", label: "功能键", type: "text" },
    { key: "value", label: "开启状态", type: "text" },
    { key: "value_type", label: "类型", type: "select", options: ["bool","int","float","string"] },
    { key: "description", label: "说明", type: "textarea" },
  ],
  constants: [
    { key: "key", label: "常量键", type: "text" },
    { key: "value", label: "数值", type: "text" },
    { key: "value_type", label: "类型", type: "select", options: ["int","float","string","bool"] },
    { key: "description", label: "说明", type: "textarea" },
  ],
  cooldowns: [
    { key: "key", label: "操作键", type: "text" },
    { key: "value", label: "冷却秒数", type: "text" },
    { key: "value_type", label: "类型", type: "select", options: ["int","float"] },
    { key: "description", label: "说明", type: "textarea" },
  ],
  realms: [
    { key: "name", label: "境界", type: "text" },
    { key: "sequence", label: "顺序", type: "number" },
    { key: "required_cultivation", label: "需求修为", type: "number" },
    { key: "base_health", label: "生命", type: "number" },
    { key: "base_mana", label: "法力", type: "number" },
    { key: "base_attack", label: "攻击", type: "number" },
    { key: "base_defense", label: "防御", type: "number" },
    { key: "base_speed", label: "速度", type: "number" },
    { key: "base_dodge", label: "闪避率", type: "number" },
    { key: "base_lifespan", label: "寿元", type: "number" },
    { key: "tribulation_base_rate", label: "渡劫率", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
  ],
  spiritual_roots: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "灵根名称", type: "text" },
    { key: "element", label: "本源属性", type: "text" },
    { key: "grade", label: "品阶", type: "text" },
    { key: "base_quality", label: "基础纯度", type: "number" },
    { key: "cultivation_bonus", label: "修炼倍率", type: "number" },
    { key: "primary_bonus", label: "主加成", type: "textarea" },
    { key: "secondary_bonus", label: "副加成", type: "textarea" },
    { key: "combat_description", label: "战斗定位", type: "textarea" },
    { key: "description", label: "图鉴描述", type: "textarea" },
    { key: "attribute_json", label: "属性项目", type: "json", jsonKind: "pairs" },
    { key: "image_url", label: "图片 URL", type: "text" },
    { key: "rarity_weight", label: "随机权重", type: "number" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  items: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "category_name", label: "类型", type: "select", options: ["丹药","材料","灵草","残卷","法宝","礼包","种子","灵肥","嵌灵宝石","生辰","任务物品"] },
    { key: "rarity_name", label: "稀有度", type: "select", options: ["凡品","灵品","仙品","神品"] },
    { key: "description", label: "说明", type: "textarea" },
    { key: "effect_type", label: "效果类型", type: "select", options: ["材料","修为","治疗比例","法力恢复比例","悟性","神魂","道心","突破","渡劫","转世","复活","修炼","礼包","种植","灵田施肥","灵兽","传送","装备嵌灵","灵根定制","称号定制","法宝定制","仙府定制","灵兽定制"] },
    { key: "effect_func", label: "效果函数", type: "text" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "effect_value", label: "效果数值", type: "number" },
    { key: "base_value", label: "基础价值", type: "number" },
    { key: "stack_limit", label: "堆叠上限", type: "number" },
    { key: "stackable", label: "可堆叠", type: "bool" },
    { key: "tradable", label: "可交易", type: "bool" },
    { key: "store_enabled", label: "商城启用", type: "bool" },
    { key: "store_price", label: "商城价格", type: "number" },
    { key: "image_url", label: "图片 URL", type: "text" },
  ],
  events: [
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["机缘","劫难","奇遇"] },
    { key: "description", label: "描述", type: "textarea" },
    { key: "probability", label: "概率", type: "number" },
    { key: "reward_json", label: "奖励项目", type: "json", jsonKind: "rewards" },
    { key: "condition_json", label: "触发条件", type: "json", jsonKind: "conditions" },
    { key: "drop_pool_id", label: "掉落池 ID", type: "number" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  tasks: [
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["日常","悬赏","宗门","成就","主线","支线"] },
    { key: "description", label: "描述", type: "textarea" },
    { key: "prerequisite_json", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "objective_json", label: "任务目标", type: "json", jsonKind: "conditions" },
    { key: "reward_json", label: "奖励项目", type: "json", jsonKind: "rewards" },
    { key: "weight", label: "权重", type: "number" },
    { key: "daily", label: "每日刷新", type: "bool" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  skills: [
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","均衡"] },
    { key: "rarity", label: "稀有度", type: "text" },
    { key: "realm_required", label: "境界条件", type: "text" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_json", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "upgrade_json", label: "升级规则", type: "json", jsonKind: "pairs" },
  ],
  pets: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "initial_power", label: "初始战力", type: "number" },
    { key: "growth_per_level", label: "每级成长", type: "number" },
    { key: "loyalty_decay", label: "忠诚衰减", type: "number" },
    { key: "evolution_condition", label: "进化条件", type: "json", jsonKind: "conditions" },
    { key: "evolution_target", label: "进化目标", type: "text" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  dungeons: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "difficulty", label: "难度", type: "select", options: ["普通","困难","噩梦","地狱"] },
    { key: "recommended_power", label: "推荐战力", type: "number" },
    { key: "stamina_cost", label: "体力消耗", type: "number" },
    { key: "reward_pool_json", label: "副本奖励", type: "json", jsonKind: "rewards" },
    { key: "daily_limit", label: "每日次数", type: "number" },
    { key: "enabled", label: "启用", type: "bool" },
    { key: "image_url", label: "图片 URL", type: "text" },
  ],
  recipes: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "materials_json", label: "所需材料", type: "json", jsonKind: "materials" },
    { key: "output_name", label: "产物", type: "text" },
    { key: "success_rate", label: "成功率", type: "number" },
    { key: "description", label: "说明", type: "textarea" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  artifacts: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "slot", label: "穿戴槽位", type: "select", options: ["本命法器","冠冕","道袍","护腕","腰佩","灵靴","戒指","项链","护符","阵盘"] },
    { key: "archetype", label: "器型", type: "text" },
    { key: "positioning", label: "战斗定位", type: "text" },
    { key: "set_name", label: "套装名称", type: "text" },
    { key: "set_bonus_json", label: "套装加成", type: "json", jsonKind: "pairs" },
    { key: "materials_json", label: "所需材料", type: "json", jsonKind: "materials" },
    { key: "attribute_json", label: "属性项目", type: "json", jsonKind: "pairs" },
    { key: "minimum_realm_sequence", label: "最低大境", type: "number" },
    { key: "minimum_realm_level", label: "最低层数", type: "number" },
    { key: "minimum_combat_power", label: "最低战力", type: "number" },
    { key: "description", label: "器物说明", type: "textarea" },
    { key: "source_json", label: "获取来源", type: "json", jsonKind: "pairs" },
    { key: "max_level", label: "强化上限", type: "number" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  synthesis_recipes: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "配方名称", type: "text" },
    { key: "category", label: "分类", type: "text" },
    { key: "materials_json", label: "所需材料", type: "json", jsonKind: "materials" },
    { key: "output_item_id", label: "产物物品 ID", type: "number" },
    { key: "output_name", label: "产物名称", type: "text" },
    { key: "output_quantity", label: "产物数量", type: "number" },
    { key: "success_rate", label: "成功率（0-1）", type: "number" },
    { key: "prerequisite_json", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "description", label: "配方说明", type: "textarea" },
    { key: "enabled", label: "启用", type: "bool" },
    { key: "sort_order", label: "排序", type: "number" },
  ],
  locations: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "地点名称", type: "text" },
    { key: "region", label: "所属区域", type: "text" },
    { key: "description", label: "地点说明", type: "textarea" },
    { key: "image_url", label: "图片 URL", type: "text" },
    { key: "npc_json", label: "地图人物", type: "json", jsonKind: "pairs" },
    { key: "tasks_json", label: "地图任务", type: "json", jsonKind: "pairs" },
    { key: "resource_name", label: "区域采集资源", type: "text" },
    { key: "resource_quantity", label: "采集数量", type: "number" },
    { key: "resource_cooldown_minutes", label: "采集刷新分钟", type: "number" },
    { key: "teleport_enabled", label: "传送阵", type: "bool" },
    { key: "cross_region_enabled", label: "跨界传送", type: "bool" },
    { key: "minimum_realm_sequence", label: "最低境界顺序", type: "number" },
    { key: "minimum_realm_level", label: "最低境界层数", type: "number" },
    { key: "minimum_level", label: "最低等级", type: "number" },
    { key: "stamina_cost", label: "移动体力", type: "number" },
    { key: "monster_name", label: "普通怪物", type: "text" },
    { key: "monster_power", label: "怪物战力", type: "number" },
    { key: "monster_encounter_rate", label: "遭遇概率", type: "number" },
    { key: "monster_reward_json", label: "妖兽奖励", type: "json", jsonKind: "rewards" },
    { key: "boss_name", label: "区域 Boss", type: "text" },
    { key: "boss_power", label: "Boss战力", type: "number" },
    { key: "boss_reward_json", label: "首领奖励", type: "json", jsonKind: "rewards" },
    { key: "boss_cooldown_minutes", label: "Boss冷却分钟", type: "number" },
    { key: "neighbors_json", label: "相邻地点", type: "json", jsonKind: "pairs" },
    { key: "enabled", label: "启用", type: "bool" },
    { key: "sort_order", label: "排序", type: "number" },
  ],
  world_leylines: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "灵脉名称", type: "text" },
    { key: "region", label: "所属界域", type: "text" },
    { key: "location_name", label: "所在地图", type: "text" },
    { key: "element", label: "本源属性", type: "text" },
    { key: "grade", label: "灵脉阶级", type: "text" },
    { key: "aura_per_minute", label: "每分钟灵气", type: "number" },
    { key: "cultivation_multiplier", label: "修炼倍率", type: "number" },
    { key: "meditation_slots", label: "打坐位", type: "number" },
    { key: "discovery_mana_cost", label: "探查法力", type: "number" },
    { key: "minimum_realm_sequence", label: "最低境界顺序", type: "number" },
    { key: "minimum_realm_level", label: "最低境界层数", type: "number" },
    { key: "minimum_combat_power", label: "最低战力", type: "number" },
    { key: "minimum_spirit", label: "最低神识", type: "number" },
    { key: "required_root_element", label: "契合灵根", type: "text" },
    { key: "required_item", label: "护脉材料", type: "text" },
    { key: "required_item_count", label: "材料数量", type: "number" },
    { key: "bonus_json", label: "独立加成", type: "json", jsonKind: "pairs" },
    { key: "description", label: "详细说明", type: "textarea" },
    { key: "image_url", label: "图片 URL", type: "text" },
    { key: "enabled", label: "启用", type: "bool" },
    { key: "sort_order", label: "排序", type: "number" },
  ],
  arena_tiers: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "段位名称", type: "text" },
    { key: "sequence", label: "段位顺序", type: "number" },
    { key: "minimum_rating", label: "晋阶积分", type: "number" },
    { key: "daily_coin", label: "每日竞技币", type: "number" },
    { key: "daily_silver", label: "每日银币", type: "number" },
    { key: "description", label: "段位道意", type: "textarea" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  titles: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "称号名", type: "text" },
    { key: "condition", label: "获取条件", type: "textarea" },
    { key: "attribute_bonus", label: "称号属性", type: "json", jsonKind: "pairs" },
    { key: "type", label: "类型", type: "text" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  activities: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "活动名", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["修炼","探索","战斗","渡劫"] },
    { key: "starts_at", label: "开始时间", type: "datetime" },
    { key: "ends_at", label: "结束时间", type: "datetime" },
    { key: "effect", label: "效果", type: "textarea" },
    { key: "effect_json", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "status", label: "状态", type: "select", options: ["未开始","进行中","已结束"] },
  ],
  mails: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "title", label: "标题", type: "text" },
    { key: "content", label: "正文", type: "textarea" },
    { key: "sender", label: "发件人", type: "text" },
    { key: "reward_json", label: "奖励项目", type: "json", jsonKind: "rewards" },
    { key: "target_type", label: "发送对象", type: "select", options: ["全部","指定玩家"] },
    { key: "target_id", label: "目标玩家", type: "text" },
    { key: "expires_at", label: "过期时间", type: "datetime" },
    { key: "sent", label: "已发送", type: "bool" },
  ],
  checkin: [
    { key: "day", label: "天数", type: "number" },
    { key: "item_name", label: "奖励物品", type: "text" },
    { key: "quantity", label: "奖励数量", type: "number" },
    { key: "special_reward", label: "特殊奖励", type: "text" },
  ],
  shop: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "item_id", label: "物品 ID", type: "number" },
    { key: "item_name", label: "物品名", type: "text" },
    { key: "currency", label: "价格类型", type: "select", options: ["灵石","银币","仙金","贡献","竞技币"] },
    { key: "price", label: "价格", type: "number" },
    { key: "sort", label: "排序", type: "number" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  cdks: [
    { key: "code", label: "兑换码", type: "text" },
    { key: "reward_json", label: "奖励项目", type: "json", jsonKind: "rewards" },
    { key: "max_uses", label: "最大次数", type: "number" },
    { key: "used_count", label: "已使用", type: "number" },
    { key: "expires_at", label: "过期时间", type: "datetime" },
    { key: "status", label: "状态", type: "select", options: ["有效","已过期","已用完"] },
  ],
  notices: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "title", label: "标题", type: "text" },
    { key: "content", label: "正文", type: "textarea" },
    { key: "type", label: "发布频道", type: "select", options: ["公告","更新","修复","全区通报"] },
    { key: "pinned", label: "置顶", type: "bool" },
    { key: "published", label: "已发布", type: "bool" },
  ],
  players: [
    { key: "account_id", label: "账号", type: "text" },
    { key: "dao_name", label: "道号", type: "text" },
    { key: "avatar_url", label: "头像 URL", type: "text" },
    { key: "gender", label: "性别", type: "text" },
    { key: "realm_name", label: "境界", type: "text" },
    { key: "realm_level", label: "境界层数", type: "number" },
    { key: "cultivation", label: "修为", type: "number" },
    { key: "cultivation_required", label: "所需修为", type: "number" },
    { key: "spiritual_root", label: "灵根", type: "text" },
    { key: "root_quality", label: "资质", type: "number" },
    { key: "health", label: "气血", type: "number" },
    { key: "max_health", label: "气血上限", type: "number" },
    { key: "mana", label: "法力", type: "number" },
    { key: "max_mana", label: "法力上限", type: "number" },
    { key: "physical_attack", label: "物攻", type: "number" },
    { key: "magic_attack", label: "法强", type: "number" },
    { key: "physical_defense", label: "物抗", type: "number" },
    { key: "magic_defense", label: "法抗", type: "number" },
    { key: "agility", label: "身法", type: "number" },
    { key: "spirit", label: "神识", type: "number" },
    { key: "perception", label: "悟性", type: "number" },
    { key: "luck", label: "气运", type: "number" },
    { key: "combat_power", label: "战力", type: "number" },
    { key: "spirit_stones", label: "灵石", type: "number" },
    { key: "silver_coins", label: "银币", type: "number" },
    { key: "immortal_jade", label: "仙金", type: "number" },
    { key: "arena_coins", label: "竞技币", type: "number" },
    { key: "merit", label: "功德", type: "number" },
    { key: "reputation", label: "声望", type: "number" },
    { key: "dao_heart", label: "道心", type: "number" },
    { key: "immortal_affinity", label: "仙缘", type: "number" },
    { key: "sect_name", label: "宗门", type: "text" },
    { key: "location", label: "位置", type: "text" },
    { key: "title", label: "称号", type: "text" },
    { key: "state", label: "状态", type: "text" },
    { key: "banned", label: "封禁", type: "bool" },
    { key: "ban_reason", label: "封禁原因", type: "textarea" },
  ],
  couples: [
    { key: "player_a_id", label: "玩家 A ID", type: "number" },
    { key: "player_b_id", label: "玩家 B ID", type: "number" },
    { key: "player_a_name", label: "玩家 A", type: "text" },
    { key: "player_b_name", label: "玩家 B", type: "text" },
    { key: "affinity", label: "道缘深度", type: "number" },
    { key: "bond_level", label: "同心等级", type: "number" },
    { key: "cultivation_bonus", label: "修炼加成", type: "number" },
    { key: "joint_attack_bonus", label: "合击加成", type: "number" },
    { key: "status", label: "状态", type: "text" },
    { key: "notes", label: "备注", type: "textarea" },
  ],
  menus: [
    { key: "parent_id", label: "父菜单 ID", type: "number" },
    { key: "menu_type", label: "菜单类型", type: "select", options: ["side","top","both"] },
    { key: "label", label: "菜单名称", type: "text" },
    { key: "icon", label: "图标文字", type: "text" },
    { key: "path", label: "路由/游戏指令", type: "text" },
    { key: "component", label: "页面组件", type: "text" },
    { key: "permission", label: "使用范围", type: "select", options: ["admin","player","viewer"] },
    { key: "sort_order", label: "排序值", type: "number" },
    { key: "is_hidden", label: "隐藏", type: "bool" },
    { key: "is_external", label: "外部链接", type: "bool" },
    { key: "external_url", label: "外部链接地址", type: "text" },
    { key: "target", label: "打开方式", type: "select", options: ["_self","_blank"] },
    { key: "badge_type", label: "角标类型", type: "select", options: ["","dot","count"] },
    { key: "badge_value", label: "角标数值", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["active","inactive"] },
  ],
  reviews: [
    { key: "type", label: "内容类型", type: "select", options: ["道号","日记","三生石","传音","留言","灵根定制","称号定制","仙府定制","灵兽定制","法宝定制","BUG反馈","玩法建议"] },
    { key: "player_id", label: "玩家 ID", type: "number" },
    { key: "player_name", label: "玩家道号", type: "text" },
    { key: "content", label: "待审内容或玩家反馈", type: "textarea" },
    { key: "status", label: "处理状态", type: "select", options: ["待审核","处理中","已通过","已拒绝","已修复"] },
    { key: "reason", label: "自动初审/人工审核说明", type: "textarea" },
    { key: "diagnosis", label: "诊断结果", type: "textarea" },
    { key: "resolution_type", label: "处理方式", type: "select", options: ["","自动数据修复","执行链排查","人工排查","玩法评审","人工评审","人工修复","退回补充","自动驳回"] },
    { key: "resolution", label: "处理结果", type: "textarea" },
    { key: "reviewed_at", label: "审核时间", type: "datetime" },
    { key: "resolved_at", label: "完成时间", type: "datetime" },
  ],
  sensitive_words: [
    { key: "word", label: "敏感词", type: "text" },
    { key: "replacement", label: "替换内容", type: "text" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  server_status: [
    { key: "metric", label: "服务器指标", type: "text" },
    { key: "value", label: "当前值", type: "text" },
  ],
  online_monitor: [
    { key: "metric", label: "在线指标", type: "text" },
    { key: "value", label: "当前值", type: "text" },
  ],
  request_stats: [
    { key: "metric", label: "请求指标", type: "text" },
    { key: "value", label: "当前值", type: "text" },
  ],
  slow_queries: [
    { key: "sql", label: "SQL", type: "textarea" },
    { key: "duration_ms", label: "耗时(ms)", type: "number" },
    { key: "source", label: "来源", type: "text" },
    { key: "created_at", label: "发生时间", type: "text" },
  ],
  performance: [
    { key: "metric", label: "性能指标", type: "text" },
    { key: "value", label: "当前值", type: "text" },
  ],
  alerts: [
    { key: "key", label: "告警项", type: "text" },
    { key: "value", label: "阈值", type: "text" },
    { key: "value_type", label: "类型", type: "select", options: ["int","float","bool"] },
    { key: "description", label: "说明", type: "textarea" },
  ],
  status_display: [
    { key: "key", label: "配置项", type: "text" },
    { key: "value", label: "图片模式（关闭后使用文字）", type: "bool" },
    { key: "value_type", label: "类型", type: "select", options: ["bool"] },
    { key: "description", label: "说明", type: "textarea" },
  ],
  owner_settings: [
    { key: "key", label: "主人配置项", type: "text" },
    { key: "value", label: "QQ开放平台用户ID", type: "text" },
    { key: "value_type", label: "类型", type: "select", options: ["string"] },
    { key: "description", label: "说明", type: "textarea" },
  ],
  managers: [
    { key: "user_id", label: "管理员用户ID", type: "text" },
    { key: "name", label: "管理员名称", type: "text" },
    { key: "role", label: "权限层级", type: "select", options: ["护法","长老","宗主","仙尊","道祖"] },
    { key: "permissions", label: "权限备注", type: "textarea" },
    { key: "enabled", label: "启用", type: "bool" },
  ],
  formations: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  talismans: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  puppets_config: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  secret_conflicts: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  inheritances: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  dao_insights: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  battlefields: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  root_evolutions: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  inner_demons: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  couple_skills: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  immortal_herbs: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  artifact_refinements: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  destiny_deductions: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  leylines: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  sect_wars: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  immortal_encounters: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
  star_realms: [
    { key: "code", label: "系统编码", type: "system" },
    { key: "name", label: "名称", type: "text" },
    { key: "type", label: "类型", type: "select", options: ["攻击","防御","辅助","成长"] },
    { key: "level", label: "等级", type: "number" },
    { key: "description", label: "描述", type: "textarea" },
    { key: "effect_params", label: "实际效果", type: "json", jsonKind: "pairs" },
    { key: "cost_materials", label: "消耗材料", type: "json", jsonKind: "materials" },
    { key: "prerequisite", label: "解锁条件", type: "json", jsonKind: "conditions" },
    { key: "sort_order", label: "排序", type: "number" },
    { key: "status", label: "状态", type: "select", options: ["启用","停用"] },
  ],
}
